# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data/original_dataset.csv")

In [3]:
data.shape

(7453, 12)

In [4]:
data.head(8)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4.0,AS5,Z,9.9,6.7,8.5,33.0,196.0
1,ACURA,ILX,COMPACT,15.0,4.0,AS5,Z,9.9,6.7,8.5,33.0,196.0
2,ACURA,ILX,COMPACT,2.4,4.0,M6,Z,11.2,7.7,9.6,29.0,221.0
3,ACURA,ILX HYBRID,COMPACT,1.5,4.0,AV7,Z,6.0,5.8,5.9,48.0,136.0
4,ACURA,MDX 4WD,SUV - SMALL,3.5,6.0,AS6,Z,12.7,9.1,11.1,25.0,255.0
5,ACURA,RDX AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.1,8.7,10.6,27.0,244.0
6,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.0,28.0,230.0
7,ACURA,TL,MID-SIZE,3.5,6.0,AS6,Z,11.8,8.1,10.1,28.0,232.0

In [5]:
data.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7450.000000,7451.000000,7443.000000,7444.000000,7444.000000,7448.000000,7443.000000
mean,3.193745,5.651080,12.780398,9.389537,11.426874,27.671187,251.027811
std,2.038318,2.296648,12.413903,16.997970,18.995393,13.881018,60.955854
min,-5.600000,2.000000,4.200000,1.200000,4.100000,-25.000000,40.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,289.000000
max,99.000000,88.000000,999.000000,999.000000,999.000000,999.000000,1239.000000

In [6]:
# finding all the null values
print(data.isnull().sum())

Make                                 0
Model                                1
Vehicle Class                        3
Engine Size(L)                       3
Cylinders                            2
Transmission                         8
Fuel Type                            4
Fuel Consumption City (L/100 km)    10
Fuel Consumption Hwy (L/100 km)      9
Fuel Consumption Comb (L/100 km)     9
Fuel Consumption Comb (mpg)          5
CO2 Emissions(g/km)                 10
dtype: int64

In [7]:
data[data["Model"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
9,ACURA,NaN,MID-SIZE,3.5,6.0,AS7,Z,12.6,9.2,10.1,25.0,259.0

In [8]:
data[(data["Make"] == "ACURA") & (data["Vehicle Class"]=="MID-SIZE")]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
6,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.00,28.0,230.0
7,ACURA,TL,MID-SIZE,3.5,6.0,AS6,Z,11.8,8.1,10.10,28.0,232.0
8,ACURA,TL AWD,MID-SIZE,3.7,6.0,AS6,Z,12.8,9.0,11.10,25.0,255.0
9,ACURA,NaN,MID-SIZE,3.5,6.0,AS7,Z,12.6,9.2,10.10,25.0,259.0
10,ACURA,TL AWD,MID-SIZE,3.7,6.0,M6,Z,13.4,9.5,11.60,24.0,267.0
11,ACURA,TL AWD,MID-SIZE,3.5,6.0,AS6,Z,11.9,8.0,9.95,-25.0,NaN
24,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.00,28.0,230.0
25,ACURA,RLX HYBRID,MID-SIZE,3.5,6.0,AM7,Z,8.0,7.5,7.70,37.0,177.0
33,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.00,28.0,235.0
34,ACURA,RLX HYBRID,MID-SIZE,3.5,6.0,AM7,Z,8.0,7.5,7.70,37.0,180.0
43,ACURA,RLX HYBRID,MID-SIZE,3.5,6.0,AM7,Z,8.2,7.8,8.10,35.0,190.0
52,ACURA,RLX HYBRID,MID-SIZE,3.5,6.0,AM7,Z,8.4,8.2,8.40,34.0,196.0
65,ACURA,RLX Hybrid,MID-SIZE,3.5,6.0,AM7,Z,8.4,8.2,8.40,34.0,196.0
76,ACURA,RLX Hybrid,MID-SIZE,3.5,6.0,AM7,Z,8.4,8.2,8.40,34.0,196.0

In [9]:
# no data looks similar to the missimg model so we are removing that row
data_prep = data.dropna(subset = "Model")

In [10]:
#check if there are model with null value
#current working data set is data_prep
data_prep.isna().sum()

Make                                 0
Model                                0
Vehicle Class                        3
Engine Size(L)                       3
Cylinders                            2
Transmission                         8
Fuel Type                            4
Fuel Consumption City (L/100 km)    10
Fuel Consumption Hwy (L/100 km)      9
Fuel Consumption Comb (L/100 km)     9
Fuel Consumption Comb (mpg)          5
CO2 Emissions(g/km)                 10
dtype: int64

In [11]:
data_prep[data_prep["Fuel Consumption Comb (mpg)"].isnull()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
22,ACURA,RDX AWD,NaN,NaN,8.0,NaN,Z,NaN,NaN,6.7,NaN,NaN
23,ACURA,RLX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.1,NaN,170.0
150,AstON MARTIN,RAPIDE S,SUBCOMPACT,6.0,12.0,NaN,Z,NaN,NaN,12.2,NaN,NaN
180,AUDI,A8L,FULL-SIZE,3.0,6.0,AS8,Z,12.6,7.7,21.0,NaN,321.0
214,AUDI,s7,SUBCOMPACT,2.0,10.0,AS8,Z,NaN,8.8,NaN,NaN,235.0

In [12]:
#having negative is not a valid value 
data_prep[data_prep["Fuel Consumption Comb (mpg)"] < 0 ]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
11,ACURA,TL AWD,MID-SIZE,3.5,6.0,AS6,Z,11.9,8.0,9.95,-25.0,NaN

In [13]:

#conversion function
def l_100km_to_mpg(l_100km):
    if l_100km > 0:  # Ensure no division by zero or negative values
        return 282.481 / l_100km
    return np.nan

#use the function in the the data_prep
# Use .loc to avoid SettingWithCopyWarning
data_prep.loc[:, 'Fuel Consumption Comb (mpg)'] = data_prep.apply(
    lambda row: l_100km_to_mpg(row['Fuel Consumption Comb (L/100 km)']) 
    if pd.isna(row['Fuel Consumption Comb (mpg)']) and not pd.isna(row['Fuel Consumption Comb (L/100 km)']) 
    else row['Fuel Consumption Comb (mpg)'],
    axis=1
)

In [14]:
data_prep[data_prep["Fuel Consumption Comb (mpg)"] < 0 ]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
11,ACURA,TL AWD,MID-SIZE,3.5,6.0,AS6,Z,11.9,8.0,9.95,-25.0,NaN

In [15]:
data_prep.loc[
    data_prep['Fuel Consumption Comb (mpg)'] < 0, 
    'Fuel Consumption Comb (mpg)'
] = data_prep.apply(
    lambda row: l_100km_to_mpg(row['Fuel Consumption Comb (L/100 km)']) 
    if pd.isna(row['Fuel Consumption Comb (mpg)']) or row['Fuel Consumption Comb (mpg)'] < 0
    else row['Fuel Consumption Comb (mpg)'],
    axis=1
)

In [16]:
data_prep[data_prep["Fuel Consumption Comb (mpg)"] < 0 ]
# success

Empty DataFrame
Columns: [Make, Model, Vehicle Class, Engine Size(L), Cylinders, Transmission, Fuel Type, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg), CO2 Emissions(g/km)]
Index: []

In [17]:
#recheck the missing values in the data set
data_prep.isna().sum()

Make                                 0
Model                                0
Vehicle Class                        3
Engine Size(L)                       3
Cylinders                            2
Transmission                         8
Fuel Type                            4
Fuel Consumption City (L/100 km)    10
Fuel Consumption Hwy (L/100 km)      9
Fuel Consumption Comb (L/100 km)     9
Fuel Consumption Comb (mpg)          1
CO2 Emissions(g/km)                 10
dtype: int64

In [18]:
data_prep[data_prep["Fuel Consumption Comb (mpg)"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
214,AUDI,s7,SUBCOMPACT,2.0,10.0,AS8,Z,NaN,8.8,NaN,NaN,235.0

In [19]:
# now we drop this as it cant be computed as the Fuel Consumption City (L/100 km) is NAN
data_prep = data_prep.dropna(subset=['Fuel Consumption Comb (mpg)'])

In [20]:
data_prep.isna().sum()

Make                                 0
Model                                0
Vehicle Class                        3
Engine Size(L)                       3
Cylinders                            2
Transmission                         8
Fuel Type                            4
Fuel Consumption City (L/100 km)     9
Fuel Consumption Hwy (L/100 km)      9
Fuel Consumption Comb (L/100 km)     8
Fuel Consumption Comb (mpg)          0
CO2 Emissions(g/km)                 10
dtype: int64

In [21]:
data_prep[data_prep.duplicated(keep=False)]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
5,ACURA,RDX AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.1,8.7,10.6,27.0,244.0
6,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.0,28.0,230.0
20,ACURA,RDX AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.1,8.7,10.6,27.0,244.0
24,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.0,28.0,230.0
36,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,226.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7408,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4.0,AS8,Z,10.8,9.5,10.2,28.0,239.0
7412,VOLVO,S60 POLESTAR,COMPACT,2.0,4.0,AS8,Z,11.8,8.5,10.3,27.0,241.0
7413,VOLVO,S60 CC T5 AWD,COMPACT,2.0,4.0,AS8,X,10.8,7.8,9.4,30.0,220.0
7418,VOLVO,V60 POLESTAR,STATION WAGON - SMALL,2.0,4.0,AS8,Z,11.8,8.5,10.3,27.0,241.0
7419,VOLVO,V60 CC T5 AWD,STATION WAGON - SMALL,2.0,4.0,AS8,X,10.8,7.8,9.4,30.0,220.0

In [22]:
#removing duplicates 
data_prep = data_prep.drop_duplicates()

In [23]:
data_prep[data_prep.duplicated(keep=False)]
#all duplicates are removed

Empty DataFrame
Columns: [Make, Model, Vehicle Class, Engine Size(L), Cylinders, Transmission, Fuel Type, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg), CO2 Emissions(g/km)]
Index: []

In [24]:
data_prep.isna().sum()

Make                                 0
Model                                0
Vehicle Class                        3
Engine Size(L)                       3
Cylinders                            2
Transmission                         8
Fuel Type                            4
Fuel Consumption City (L/100 km)     9
Fuel Consumption Hwy (L/100 km)      9
Fuel Consumption Comb (L/100 km)     8
Fuel Consumption Comb (mpg)          0
CO2 Emissions(g/km)                 10
dtype: int64

In [25]:
data_prep[data_prep["CO2 Emissions(g/km)"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
11,ACURA,TL AWD,MID-SIZE,3.5,6.0,AS6,Z,11.9,8.0,9.95,28.390050,NaN
15,ACURA,Tsx,COMPACT,2.7,4.0,NaN,Z,15.5,NaN,NaN,25.000000,NaN
22,ACURA,RDX AWD,NaN,NaN,8.0,NaN,Z,NaN,NaN,6.70,42.161343,NaN
148,AstON MARTIN,RAPIDE S,SUBCOMPACT,5.0,11.0,A8,Z,15.2,NaN,NaN,15.000000,NaN
149,AstON MARTIN,RAPIDE S,SUBCOMPACT,4.0,8.0,NaN,NaN,NaN,NaN,NaN,19.000000,NaN
150,AstON MARTIN,RAPIDE S,SUBCOMPACT,6.0,12.0,NaN,Z,NaN,NaN,12.20,23.154180,NaN
212,AUDI,A6 QUATTRO,SUBCOMPACT,4.2,4.0,AS8,Z,NaN,9.5,NaN,11.000000,NaN
213,AUDI,A6 QUATTRO,MID-SIZE,2.0,6.0,A7,Z,NaN,8.1,NaN,15.000000,NaN
215,AUDI,s7,MID-SIZE,3.0,8.0,A7,Z,NaN,NaN,12.00,23.000000,NaN
216,AUDI,s7,SUBCOMPACT,3.0,4.0,AS8,Z,14.2,NaN,NaN,21.000000,NaN

In [26]:
#remove rows where the CO2 Emissions(g/km) is NAN
# co2 emissions cant be calculated with available data
data_prep = data_prep.dropna(subset=['CO2 Emissions(g/km)'])

In [27]:
data_prep[data_prep['CO2 Emissions(g/km)'].isna()]

Empty DataFrame
Columns: [Make, Model, Vehicle Class, Engine Size(L), Cylinders, Transmission, Fuel Type, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg), CO2 Emissions(g/km)]
Index: []

In [28]:
data_prep.isna().sum()

Make                                0
Model                               0
Vehicle Class                       2
Engine Size(L)                      2
Cylinders                           2
Transmission                        4
Fuel Type                           3
Fuel Consumption City (L/100 km)    3
Fuel Consumption Hwy (L/100 km)     2
Fuel Consumption Comb (L/100 km)    2
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [29]:
data_prep[data_prep["Engine Size(L)"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
21,ACURA,ILX,COMPACT,NaN,NaN,NaN,NaN,NaN,5.8,NaN,28.000000,140.0
23,ACURA,RLX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.1,46.308361,170.0

In [30]:
# remove row where the Engine Size(L) cos most colom are NAN
data_prep = data_prep.dropna(subset=['Engine Size(L)'])

In [31]:
data_prep[data_prep["Engine Size(L)"].isna()]

Empty DataFrame
Columns: [Make, Model, Vehicle Class, Engine Size(L), Cylinders, Transmission, Fuel Type, Fuel Consumption City (L/100 km), Fuel Consumption Hwy (L/100 km), Fuel Consumption Comb (L/100 km), Fuel Consumption Comb (mpg), CO2 Emissions(g/km)]
Index: []

In [32]:
data_prep.isna().sum()

Make                                0
Model                               0
Vehicle Class                       1
Engine Size(L)                      0
Cylinders                           0
Transmission                        2
Fuel Type                           1
Fuel Consumption City (L/100 km)    1
Fuel Consumption Hwy (L/100 km)     1
Fuel Consumption Comb (L/100 km)    1
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [33]:
data_prep[data_prep["Transmission"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
147,AstON MARTIN,DB11 V12,MINICOMPACT4,4.0,14.0,NaN,NaN,NaN,14.4,12.1,18.0,363.0
590,BMW,335i SEDAN,COMPACT,10.0,2.0,NaN,Z,11.5,8.0,NaN,72.0,85.0

In [34]:
data_prep = data_prep.dropna(subset=['Fuel Type'])

In [35]:
data_prep.loc[data_prep['Fuel Consumption Comb (L/100 km)'].isna(), 'Fuel Consumption Comb (L/100 km)'] = (
    data_prep['Fuel Consumption City (L/100 km)'] + data_prep['Fuel Consumption Hwy (L/100 km)']
) / 2

In [36]:
data_prep[data_prep["Transmission"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
590,BMW,335i SEDAN,COMPACT,10.0,2.0,NaN,Z,11.5,8.0,9.75,72.0,85.0

In [37]:
data_prep = data_prep.dropna(subset=['Transmission'])

In [38]:
data_prep.isna().sum()

Make                                0
Model                               0
Vehicle Class                       1
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     1
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [39]:
data_prep[data_prep["Vehicle Class"].isna()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
55,ACURA,TLX SH-AWD,NaN,3.5,6.0,AS9,Z,11.4,7.7,9.8,29.0,228.0

In [40]:
# check what could be the Vehicle class
data_prep[(data_prep["Make"] == "ACURA") & (data_prep["Model"] == "TLX SH-AWD") ]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
28,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,221.0
36,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,226.0
55,ACURA,TLX SH-AWD,NaN,3.5,6.0,AS9,Z,11.4,7.7,9.8,29.0,228.0
56,ACURA,TLX SH-AWD,COMPACT,-5.6,6.0,AS10,Z,10.0,1.2,5.6,30.0,228.0
68,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.4,7.7,9.8,29.0,228.0

In [41]:
data_prep.loc[data_prep["Vehicle Class"].isnull(), "Vehicle Class"] = "COMPACT"

In [42]:
data_prep[(data_prep["Make"] == "ACURA") & (data_prep["Model"] == "TLX SH-AWD") ]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
28,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,221.0
36,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,226.0
55,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.4,7.7,9.8,29.0,228.0
56,ACURA,TLX SH-AWD,COMPACT,-5.6,6.0,AS10,Z,10.0,1.2,5.6,30.0,228.0
68,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.4,7.7,9.8,29.0,228.0

In [43]:
# engine size cant be negative 
data_prep[(data_prep["Engine Size(L)"] < 0 )]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
56,ACURA,TLX SH-AWD,COMPACT,-5.6,6.0,AS10,Z,10.0,1.2,5.6,30.0,228.0

In [44]:
filtered_data = data_prep[(data_prep['Make'] == 'ACURA') &
                     (data_prep['Model'] == 'TLX SH-AWD') &
                     (data_prep['Cylinders'] == 6.0)]


filtered_data['Engine Size(L)'].value_counts()

Engine Size(L)
 3.5    4
-5.6    1
Name: count, dtype: int64

In [45]:
# Replace negative values in the 'Engine Size (L)' column with 3.5
#as that is the frequent size 
data_prep['Engine Size(L)'] = data_prep.apply(
    lambda row: 3.5 if row['Engine Size(L)'] < 0 else row['Engine Size(L)'],
    axis=1
)

In [46]:
data_prep["Engine Size(L)"].unique()

array([ 2. , 15. ,  2.4,  1.5,  3.5,  3.7,  3. ,  1.8,  2.9,  5.9,  4.7,
        6. ,  5.2,  4. , 12. ,  6.3,  4.2,  2.5,  6.8,  4.4, 24.4,  6.6,
        8. ,  3.6,  1.4,  1.2,  1.3,  6.2,  2.7,  4.3,  5.3,  4.8,  2.8,
        1.6,  5.7,  6.4,  8.4, 13.6,  4.6,  5.4,  5. ,  1. ,  5.8,  2.3,
        3.3,  3.8,  5.6,  3.2,  6.5,  3.4,  2.2,  5.5,  2.1, 88. ,  6.7,
        0.9, 99. ])

In [47]:
data_prep.isna().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     1
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [48]:
# Checking for missing values in the "Fuel Consumption Hwy (L/100 km)" column
data_prep[data_prep[["Fuel Consumption Hwy (L/100 km)"]].isnull().any(axis = 1)]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
211,AUDI,s7,MID-SIZE,4.0,6.0,A7,Z,12.0,NaN,10.4,18.0,240.0

In [49]:
# Calculating and filling missing values for the "Fuel Consumption Hwy (L/100 km)" column based on a percentage of the combined consumption
mask = data_prep["Fuel Consumption Hwy (L/100 km)"].isnull()
mask.value_counts()

Fuel Consumption Hwy (L/100 km)
False    6330
True        1
Name: count, dtype: int64

In [50]:
# there is one missing value we are finding the val based on the impact percentage
data_prep.loc[mask, "Fuel Consumption Hwy (L/100 km)"] = data_prep.loc[mask, "Fuel Consumption Comb (L/100 km)"] * 0.45

In [51]:
data_prep.isna().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [52]:
# data_prep.to_csv('data/preprocessig_data.csv', index=False)

### all null values are dealed with now we will see the unique values

In [53]:
# check each colume and normalize
data_prep.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [54]:
data_prep["Make"].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUGATTI', 'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE',
       'FIAT', 'FORD', 'GENESIS', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI',
       'JAGUAR', 'JEEP', 'KIA', 'LAMBORGHINI',
       'LAMBORGHINI Aventador Coupe', 'LAND ROVER',
       'LAND ROVER Range Rover SVAutobiography Dynamic', 'LEXUS',
       'LEXUS UX 250h AWD', 'LINCOLN', 'MASERATI', 'MAZDA',
       'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN', 'PORSCHE', 'RAM',
       'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU', 'TOYOTA',
       'VOLKSWAGEN', 'VOLVO'], dtype=object)

In [55]:
data_prep["Make"].value_counts().sort_index()

Make
ACURA                                              54
ALFA ROMEO                                         20
ASTON MARTIN                                       39
AUDI                                              271
BENTLEY                                            36
BMW                                               502
BUGATTI                                             2
BUICK                                              92
CADILLAC                                          141
CHEVROLET                                         518
CHRYSLER                                           64
DODGE                                             183
FIAT                                               56
FORD                                              580
GENESIS                                            14
GMC                                               291
HONDA                                             164
HYUNDAI                                           184
INFINITI                                           87
JAGUAR                                            118
JEEP                                              202
KIA                                               192
LAMBORGHINI                                        37
LAMBORGHINI Aventador Coupe                         1
LAND ROVER                                         77
LAND ROVER Range Rover SVAutobiography Dynamic      1
LEXUS                                             129
LEXUS UX 250h AWD                                   1
LINCOLN                                            81
MASERATI                                           53
MAZDA                                             128
MERCEDES-BENZ                                     369
MINI                                              201
MITSUBISHI                                         74
NISSAN                                            213
PORSCHE                                           297
RAM                                                73
ROLLS-ROYCE                                        49
SCION                                              21
SMART                                               7
SRT                                                 2
SUBARU                                            120
TOYOTA                                            282
VOLKSWAGEN                                        187
VOLVO                                             118
Name: count, dtype: int64

In [56]:
# change "LAMBORGHINI Aventador Coupe" to "LAMBORGHINI" and  "LAND ROVER Range Rover SVAutobiography Dynamic" to "LAND ROVER"
# and "LEXUS UX 250h AWD" to "LEXUS"

data_prep[data_prep["Make"] == "LAMBORGHINI Aventador Coupe"]["Make"].count()

np.int64(1)

In [57]:
data_prep["Make"].replace({
    "LAMBORGHINI Aventador Coupe" : "LAMBORGHINI",
    "LAND ROVER Range Rover SVAutobiography Dynamic" : "LAND ROVER",
    "LEXUS UX 250h AWD" : "LEXUS"
},inplace=True)

/var/folders/0g/0md2jbv942960wxy1_y9l3h40000gn/T/ipykernel_4415/1882782351.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_prep["Make"].replace({

In [58]:
data_prep["Make"].value_counts()

Make
FORD             580
CHEVROLET        518
BMW              502
MERCEDES-BENZ    369
PORSCHE          297
GMC              291
TOYOTA           282
AUDI             271
NISSAN           213
JEEP             202
MINI             201
KIA              192
VOLKSWAGEN       187
HYUNDAI          184
DODGE            183
HONDA            164
CADILLAC         141
LEXUS            130
MAZDA            128
SUBARU           120
VOLVO            118
JAGUAR           118
BUICK             92
INFINITI          87
LINCOLN           81
LAND ROVER        78
MITSUBISHI        74
RAM               73
CHRYSLER          64
FIAT              56
ACURA             54
MASERATI          53
ROLLS-ROYCE       49
ASTON MARTIN      39
LAMBORGHINI       38
BENTLEY           36
SCION             21
ALFA ROMEO        20
GENESIS           14
SMART              7
SRT                2
BUGATTI            2
Name: count, dtype: int64

In [59]:
data_prep["Model"].unique()

array(['ILX', 'ILX HYBRID', 'MDX 4WD', ..., 'V90 CC T5 AWD',
       'XC40 T5 AWD', 'XC40 T4 AWD'], dtype=object)

In [60]:
# Get unique values from the 'Model' column and store them in 'unique_values'
unique_values = data_prep['Model'].unique()

# Create an empty list 'array1' to hold the unique values
array1 = []


# Iterate through each unique value and append it to 'array1'
for value in unique_values:
    # print(value)
    array1.append(value)

# Sort the 'array1' to get a list of unique values in alphabetical order
sorted_list = sorted(array1)
# sorted_list

In [61]:
sorted_list

[' 1500 eTorque',
 ' 4C',
 ' 4Runner 4WD',
 ' 911 Carrera S',
 ' A4 QUATTRO',
 ' A6 QUATTRO',
 ' AMG C 43 4MATIC',
 ' CX-3',
 ' Cooper 3 Door',
 ' Crosstrek AWD',
 ' E 550 4MATIC',
 ' E 550 CABRIOLET',
 ' E 63 AMG 4MATIC WAGON',
 ' Eclipse Cross 4WD',
 ' F-150 FFV (Payload Pkg)',
 ' GT',
 ' Ghibli',
 ' Phantom',
 ' Sienna',
 ' Transit Connect Van FFV',
 '124 SPIDER',
 '124 Spider',
 '1500',
 '1500 (MDS)',
 '1500 4X4',
 '1500 4X4 (MDS)',
 '1500 4X4 DIESEL',
 '1500 4X4 ECODIESEL',
 '1500 4X4 EcoDiesel',
 '1500 4X4 FFV',
 '1500 4X4 eTorque',
 '1500 Classic',
 '1500 Classic 4X4',
 '1500 Classic 4X4 EcoDiesel',
 '1500 Classic 4X4 FFV',
 '1500 Classic EcoDiesel',
 '1500 Classic FFV',
 '1500 DIESEL',
 '1500 ECODIESEL',
 '1500 ECODIESEL HFE',
 '1500 EcoDiesel',
 '1500 FFV',
 '1500 HFE',
 '1500 HFE eTorque',
 '1500 eTorque',
 '200',
 '200 AWD',
 '200 AWD FFV',
 '200 CONVERTIBLE',
 '200 CONVERTIBLE FFV',
 '200 FFV',
 '200 SEDAN',
 '200 SEDAN FFV',
 '228i',
 '228i CABRIOLET',
 '228i COUPE',
 '228i xDRIVE',
 '228i xDRIVE CABRIOLET',
 '228i xDRIVE COUPE',
 '230i CABRIOLET',
 '230i COUPE',
 '230i Cabriolet',
 '230i Coupe',
 '230i xDRIVE CABRIOLET',
 '230i xDRIVE COUPE',
 '230i xDrive Cabriolet',
 '230i xDrive Coupe',
 '300',
 '300 (MDS)',
 '300 AWD',
 '300 AWD (MDS)',
 '300 AWD FFV',
 '300 FFV',
 '300 SRT (MDS)',
 '320i',
 '320i SEDAN',
 '320i xDRIVE',
 '320i xDRIVE SEDAN',
 '328d xDRIVE',
 '328d xDRIVE SEDAN',
 '328d xDRIVE TOURING',
 '328i',
 '328i SEDAN',
 '328i xDRIVE',
 '328i xDRIVE GRAN TURISMO',
 '328i xDRIVE SEDAN',
 '328i xDRIVE TOURING',
 '330i xDRIVE',
 '330i xDRIVE GRAN TURISMO',
 '330i xDRIVE TOURING',
 '330i xDrive',
 '330i xDrive Gran Turismo',
 '330i xDrive Sedan',
 '330i xDrive Touring',
 '335i',
 '335i SEDAN',
 '335i xDRIVE',
 '335i xDRIVE GRAN TURISMO',
 '335i xDRIVE SEDAN',
 '340i',
 '340i xDRIVE',
 '340i xDRIVE GRAN TURISMO',
 '370Z',
 '370Z COUPE',
 '370Z ROADSTER',
 '370Z Roadster',
 '428i CABRIOLET',
 '428i COUPE',
 '428i GRAN COUPE',
 '428i xDRIVE CABRIOLET',
 '428i xDRIVE COUPE',
 '428i xDRIVE GRAN COUPE',
 '430i Coupe',
 '430i xDRIVE CABRIOLET',
 '430i xDRIVE COUPE',
 '430i xDRIVE GRAN COUPE',
 '430i xDrive Cabriolet',
 '430i xDrive Coupe',
 '430i xDrive Gran Coupe',
 '435i CABRIOLET',
 '435i COUPE',
 '435i GRAN COUPE',
 '435i xDRIVE CABRIOLET',
 '435i xDRIVE COUPE',
 '435i xDRIVE GRAN COUPE',
 '440i COUPE',
 '440i Coupe',
 '440i xDRIVE CABRIOLET',
 '440i xDRIVE COUPE',
 '440i xDRIVE GRAN COUPE',
 '440i xDrive Cabriolet',
 '440i xDrive Coupe',
 '440i xDrive Gran Coupe',
 '4C',
 '4C COUPE',
 '4C Coupe',
 '4C SPIDER',
 '4C Spider',
 '4RUNNER (Part-Time 4WD)',
 '4RUNNER 4WD',
 '4RUNNER 4WD (Part-Time 4WD)',
 '4Runner 4WD',
 '4Runner 4WD (Part-Time 4WD)',
 '500',
 '500 ABARTH',
 '500 ABARTH CABRIO',
 '500 ABARTH HATCHBACK',
 '500 CABRIO',
 '500 CABRIO TURBO',
 '500 HATCHBACK',
 '500 HATCHBACK TURBO',
 '500L',
 '500L TURBO',
 '500X',
 '500X AWD',
 '528i',
 '528i SEDAN',
 '528i xDRIVE',
 '528i xDRIVE SEDAN',
 '530i xDRIVE',
 '530i xDrive',
 '530i xDrive Sedan',
 '535d xDRIVE',
 '535d xDRIVE SEDAN',
 '535i xDRIVE',
 '535i xDRIVE GRAN TURISMO',
 '535i xDRIVE SEDAN',
 '540i xDRIVE',
 '540i xDrive',
 '540i xDrive Sedan',
 '550i xDRIVE',
 '550i xDRIVE GRAN TURISMO',
 '550i xDRIVE SEDAN',
 '640i xDRIVE CABRIOLET',
 '640i xDRIVE GRAN COUPE',
 '640i xDRIVE GRAN TURISMO',
 '640i xDrive Gran Coupe',
 '640i xDrive Gran Turismo',
 '650i xDRIVE CABRIOLET',
 '650i xDRIVE COUPE',
 '650i xDRIVE GRAN COUPE',
 '650i xDrive Gran Coupe',
 '740Ld xDRIVE SEDAN',
 '740Li xDRIVE',
 '740Li xDRIVE SEDAN',
 '750Li xDRIVE',
 '750Li xDRIVE SEDAN',
 '750Li xDrive',
 '750Li xDrive Sedan',
 '750i xDRIVE',
 '750i xDRIVE SEDAN',
 '750i xDRIVE SWB',
 '750i xDrive',
 '750i xDrive Sedan',
 '760Li',
 '760Li SEDAN',
 '86',
 '911 CARRERA',
 '911 CARRERA 4',
 '911 CARRERA 4 CABRIOLET',
 '911 CARRERA 4 GTS',
 '911 CARRERA 4 GTS CABRIOLET',
 '911 CARRERA 4S',
 '911 CARRERA 4S CABRIOLET',
 '911 CARRERA CABRIOLET',
 '911 CARRERA GTS',
 '911 CARRERA GTS CABRIOLET',
 '911 CARRERA S',
 '911 CARRERA S CABRIOLET',
 '911 Carrera',
 '911 Carrera 4',
 '911 Carrera 4 Cabriolet',
 '911 Carrera 4 GTS',
 '911 Carrera 4 GTS Cabriolet',
 '911 Carrera 4S',
 '911 Carrera 4S Cabriolet',
 '911 Carrera Cabriolet',
 '911 Carrera GTS',
 '911 Carrera GTS Cabriolet',
 '911 Carrera S',
 '911 Carrera S Cabriolet',
 '911 Carrera T',
 '911 GT2 RS',
 '911 GT3',
 '911 GT3 RS',
 '911 GT3 Touring',
 '911 GT3RS',
 '911 Speedster',
 '911 TARGA 4',
 '911 TARGA 4 GTS',
 '911 TARGA 4S',
 '911 TURBO',
 '911 TURBO CABRIOLET',
 '911 TURBO S',
 '911 TURBO S CABRIOLET',
 '911 TURBO S EXCLUSIVE',
 '911 Targa 4',
 '911 Targa 4 GTS',
 '911 Targa 4S',
 '911 Turbo',
 '911 Turbo Cabriolet',
 '911 Turbo S',
 '911 Turbo S Cabriolet',
 '911 Turbo S Exclusive Cabriolet',
 'A 220',
 'A 220 4MATIC',
 'A 250',
 'A 250 4MATIC',
 'A3',
 'A3 CABRIOLET QUATTRO',
 'A3 Cabriolet quattro',
 'A3 QUATTRO',
 'A3 TDI (modified)',
 'A3 quattro',
 'A4',
 'A4 ALLROAD QUATTRO',
 'A4 QUATTRO',
 'A4 ULTRA',
 'A4 allroad quattro',
 'A4 quattro',
 'A5 CABRIOLET QUATTRO',
 'A5 Cabriolet quattro',
 'A5 QUATTRO',
 'A5 SPORTBACK QUATTRO',
 'A5 Sportback quattro',
 'A5 quattro',
 'A6 QUATTRO',
 'A6 QUATTRO TDI (modified)',
 'A6 allroad',
 'A6 quattro',
 'A7 QUATTRO',
 'A7 QUATTRO TDI (modified)',
 'A7 quattro',
 'A8',
 'A8 QUATTRO',
 'A8 QUATTRO TDI (modified)',
 'A8 TDI (modified)',
 'A8L',
 'A8L QUATTRO',
 'A8L TDI (modified)',
 'ACADIA',
 'ACADIA AWD',
 'ACCENT',
 'ACCORD',
 'ACCORD COUPE',
 'ACCORD HYBRID',
 'ACCORD SEDAN',
 'ACCORD SPORT',
 'ACCORD SPORT/TOURING',
 'ACTIVEHYBRID 3',
 'ACTIVEHYBRID 5',
 'ACTIVEHYBRID 7L',
 'ALLROAD QUATTRO',
 'ALPINA B6 xDRIVE GRAN COUPE',
 'ALPINA B7 xDRIVE',
 'ALPINA B7 xDRIVE LWB',
 'ALPINA B7 xDRIVE SWB',
 'ALTIMA',
 'ALTIMA 3.5',
 'ALTIMA SR',
 'AMG C 43 4MATIC',
 'AMG C 43 4MATIC CABRIOLET',
 'AMG C 43 4MATIC COUPE',
 'AMG C 43 4MATIC Cabriolet',
 'AMG C 43 4MATIC Coupe',
 'AMG C 43 4MATIC Wagon',
 'AMG C 63',
 'AMG C 63 CABRIOLET',
 'AMG C 63 COUPE',
 'AMG C 63 S',
 'AMG C 63 S CABRIOLET',
 'AMG C 63 S COUPE',
 'AMG C 63 S Cabriolet',
 'AMG C 63 S Coupe',
 'AMG CLA 45',
 'AMG CLA 45 4MATIC',
 'AMG CLS 53 4MATIC+',
 'AMG CLS 63 S 4MATIC',
 'AMG E 43 4MATIC',
 'AMG E 53 4MATIC+',
 'AMG E 53 4MATIC+ Cabriolet',
 'AMG E 53 4MATIC+ Coupe',
 'AMG E 53 4MATIC+ Wagon',
 'AMG E 63 S 4MATIC',
 'AMG E 63 S 4MATIC WAGON',
 'AMG E 63 S 4MATIC+',
 'AMG E 63 S 4MATIC+ Wagon',
 'AMG G 63',
 'AMG G 65',
 'AMG GL 63 S',
 'AMG GLA 45',
 'AMG GLA 45 4MATIC',
 'AMG GLC 43 4MATIC',
 'AMG GLC 43 4MATIC COUPE',
 'AMG GLC 43 4MATIC Coupe',
 'AMG GLC 63 S 4MATIC+',
 'AMG GLC 63 S 4MATIC+ Coupe',
 'AMG GLE 43 4MATIC',
 'AMG GLE 43 4MATIC COUPE',
 'AMG GLE 43 4MATIC Coupe',
 'AMG GLE 63 S 4MATIC',
 'AMG GLE 63 S 4MATIC COUPE',
 'AMG GLE 63 S 4MATIC Coupe',
 'AMG GLE 63 S COUPE 4MATIC',
 'AMG GLS 63',
 'AMG GLS 63 4MATIC',
 'AMG GT 53 4MATIC+ Coupe',
 'AMG GT 63 4MATIC+ Coupe',
 'AMG GT 63 S 4MATIC+ Coupe',
 'AMG GT C COUPE',
 'AMG GT C Coupe',
 'AMG GT C ROADSTER',
 'AMG GT C Roadster',
 'AMG GT COUPE',
 'AMG GT R COUPE',
 'AMG GT R Coupe',
 'AMG GT ROADSTER',
 'AMG GT S',
 'AMG GT S COUPE',
 'AMG S 63',
 'AMG S 63 4MATIC',
 'AMG S 63 4MATIC CABRIOLET',
 'AMG S 63 4MATIC COUPE',
 'AMG S 63 4MATIC+',
 'AMG S 63 4MATIC+ Cabriolet',
 'AMG S 63 4MATIC+ Coupe',
 'AMG S 63 CABRIOLET',
 'AMG S 63 COUPE',
 'AMG S 65',
 'AMG S 65 CABRIOLET',
 'AMG S 65 COUPE',
 'AMG S 65 Cabriolet',
 'AMG S 65 Coupe',
 'AMG SL 63',
 'AMG SL 65',
 'AMG SLC 43',
 'AMG SLK 55',
 'ARMADA 4WD',
 'ATLAS',
 'ATLAS 4MOTION',
 'ATS',
 'ATS AWD',
 'ATS-V',
 'AVALON',
 'AVENGER',
 'AVENGER FFV',
 'AVENTADOR COUPE',
 'AVENTADOR COUPE LP 740',
 'AVENTADOR ROADSTER',
 'AVENTADOR ROADSTER LP 740',
 'AVENTADOR S COUPE',
 'AVENTADOR S ROADSTER',
 'Acadia',
 'Acadia AWD',
 'Accent',
 'Accord',
 'Accord Hybrid',
 'Accord Sport/Touring',
 'Alpina B6 xDrive Gran Coupe',
 'Alpina B7 xDrive',
 'Altima',
 'Altima AWD',
 'Altima AWD SR/Platinum',
 'Altima SR/Platinum',
 'Armada 4WD',
 'Arteon 4MOTION',
 'Ascent AWD',
 'Atlas',
 'Atlas 4MOTION',
 'Atlas Cross Sport 4MOTION',
 'Avalon',
 'Aventador Coupe',
 'Aventador Roadster',
 'Aviator',
 'B 250',
 'B 250 4MATIC',
 'BEETLE',
 'BEETLE CONVERTIBLE',
 'BEETLE DUNE',
 'BEETLE DUNE CONVERTIBLE',
 'BEETLE TDI (modified)',
 'BENTAYGA',
 'BOXSTER',
 'BOXSTER GTS',
 'BOXSTER S',
 'BOXSTER SPYDER',
 'BRZ',
 'BRZ tS',
 'Beetle',
 'Beetle Convertible',
 'Beetle Dune',
 'Beetle Dune Convertible',
 'Bentayga',
 'Blazer',
 'Blazer AWD',
 'Boxster',
 'Boxster GTS',
 'Boxster S',
 'C 250',
 'C 250 COUPE',
 'C 300 4MATIC',
 'C 300 4MATIC CABRIOLET',
 'C 300 4MATIC COUPE',
 'C 300 4MATIC Cabriolet',
 'C 300 4MATIC Coupe',
 'C 300 4MATIC FFV',
 'C 300 4MATIC WAGON',
 'C 300 4MATIC Wagon',
 'C 350',
 'C 350 4MATIC',
 'C 350 4MATIC COUPE',
 'C 350 COUPE',
 'C 400 4MATIC',
 'C 450 AMG SPORT 4MATIC',
 'C 63 AMG',
 'C 63 AMG COUPE',
 'C-HR',
 'C-MAX HYBRID',
 'CADENZA',
 'CAMARO',
 'CAMARO 2LS',
 'CAMARO SS',
 'CAMARO Z/28',
 'CAMARO ZL1',
 'CAMRY',
 'CAMRY HYBRID LE',
 'CAMRY HYBRID XLE/SE',
 'CAMRY LE/SE',
 'CAMRY XLE/XSE',
 'CAMRY XSE',
 'CANYON',
 'CANYON 4WD',
 'CARGO VAN FFV',
 'CAYENNE',
 'CAYENNE DIESEL (modified)',
 'CAYENNE GTS',
 'CAYENNE PLATINUM',
 'CAYENNE S',
 'CAYENNE S HYBRID',
 'CAYENNE TURBO',
 'CAYENNE TURBO S',
 'CAYMAN',
 'CAYMAN GT4',
 'CAYMAN GTS',
 'CAYMAN S',
 'CC',
 'CC 4MOTION',
 'CHALLENGER',
 'CHALLENGER (MDS)',
 'CHALLENGER GT',
 'CHALLENGER GT AWD',
 'CHALLENGER GT AWD FFV',
 'CHALLENGER SRT',
 'CHALLENGER SRT (MDS)',
 'CHALLENGER SRT DEMON',
 'CHALLENGER SRT HELLCAT',
 'CHARGER',
 'CHARGER (MDS)',
 'CHARGER AWD',
 'CHARGER AWD (MDS)',
 'CHARGER AWD FFV',
 'CHARGER FFV',
 'CHARGER SRT (MDS)',
 'CHARGER SRT 392 HEMI',
 'CHARGER SRT HELLCAT',
 'CHEROKEE',
 'CHEROKEE 4X4',
 'CHEROKEE 4X4 ACTIVE DRIVE I',
 'CHEROKEE 4X4 ACTIVE DRIVE I FFV',
 'CHEROKEE 4X4 ACTIVE DRIVE II',
 'CHEROKEE 4X4 ACTIVE DRIVE LOCK',
 'CHEROKEE 4X4 FFV',
 'CHEROKEE FFV',
 'CHEROKEE TRAILHAWK 4X4',
 'CHIRON',
 'CITY EXPRESS',
 'CIVIC',
 'CIVIC COUPE',
 'CIVIC COUPE Si',
 'CIVIC HATCHBACK',
 'CIVIC HATCHBACK SPORT',
 'CIVIC HYBRID',
 'CIVIC SEDAN',
 'CIVIC SEDAN Si',
 'CIVIC Si',
 'CIVIC TYPE R',
 'CL 550 4MATIC',
 'CL 63 AMG',
 'CLA 250',
 'CLA 250 4MATIC',
 'CLA 250 4MATIC FFV',
 'CLA 45 AMG',
 'CLA 45 AMG 4MATIC',
 'CLS 400 4MATIC',
 'CLS 450 4MATIC',
 'CLS 550 4MATIC',
 'CLS 63 AMG 4MATIC',
 'CLS 63 AMG S 4MATIC',
 'COLORADO',
 'COLORADO 4WD',
 'COLORADO ZR2 4WD',
 'COMPASS',
 'COMPASS 4X4',
 'COMPASS 4X4 TRAIL RATED',
 'CONTINENTAL AWD',
 'CONTINENTAL GT',
 'CONTINENTAL GT CONVERTIBLE',
 'CONTINENTAL GT SPEED CONVERTIBLE',
 'CONTINENTAL GT3-R',
 'CONTINENTAL GTC',
 'CONTINENTAL SUPERSPORTS',
 'COOPER 3 DOOR',
 'COOPER 5 DOOR',
 'COOPER CLUBMAN',
 'COOPER CLUBMAN ALL4',
 'COOPER CONVERTIBLE',
 'COOPER COUNTRYMAN',
 'COOPER COUNTRYMAN ALL4',
 'COOPER COUPE',
 'COOPER PACEMAN',
 'COOPER ROADSTER',
 'COOPER S 3 DOOR',
 'COOPER S 5 DOOR',
 'COOPER S CLUBMAN',
 'COOPER S CLUBMAN ALL4',
 'COOPER S CONVERTIBLE',
 'COOPER S COUNTRYMAN  ALL4',
 'COOPER S COUNTRYMAN ALL4',
 'COOPER S COUPE',
 'COOPER S PACEMAN ALL4',
 'COOPER S ROADSTER',
 'COROLLA',
 'COROLLA LE ECO (1-mode)',
 'COROLLA LE ECO (2-mode)',
 'COROLLA MATRIX',
 'COROLLA iM',
 'CORVETTE',
 'CORVETTE Z06',
 'CR-V',
 'CR-V AWD',
 'CR-Z',
 'CROSSTOUR AWD',
 'CROSSTREK AWD',
 'CRUZE',
 'CRUZE DIESEL',
 'CRUZE ECO',
 'CRUZE HATCHBACK',
 'CRUZE HATCHBACK DIESEL',
 'CRUZE HATCHBACK PREMIER',
 'CRUZE LIMITED',
 'CRUZE LIMITED ECO',
 'CRUZE PREMIER',
 'CT 200h',
 'CT4',
 'CT4 AWD',
 'CT4-V',
 'CT4-V AWD',
 'CT5',
 'CT5 AWD',
 'CT5-V',
 'CT5-V AWD',
 'CT6',
 'CT6 AWD',
 'CTS',
 'CTS AWD',
 'CTS COUPE',
 'CTS COUPE AWD',
 'CTS SEDAN',
 'CTS SEDAN AWD',
 'CTS SEDAN Vsport',
 'CTS SPORT WAGON',
 'CTS SPORT WAGON AWD',
 'CTS Vsport',
 'CTS-V',
 'CTS-V COUPE',
 'CTS-V SEDAN',
 'CTS-V SPORT WAGON',
 'CX-3',
 'CX-3 (SIL)',
 'CX-3 4WD',
 'CX-30',
 'CX-30 4WD',
 'CX-30 4WD (Cylinder Deactivation)',
 'CX-5',
 'CX-5 ',
 'CX-5 (Cylinder Deactivation)',
 'CX-5 (SIL)',
 'CX-5 4WD',
 'CX-5 4WD (Cylinder Deactivation)',
 'CX-5 Diesel 4WD',
 'CX-5 Turbo 4WD',
 'CX-9',
 'CX-9 4WD',
 'Cadenza',
 'Camaro',
 'Camaro SS',
 'Camaro ZL1',
 'Camry',
 'Camry AWD LE/SE',
 'Camry AWD XLE/XSE',
 'Camry Hybrid LE',
 'Camry Hybrid XLE/SE',
 'Camry LE/SE',
 'Camry TRD',
 'Camry XLE/XSE',
 'Camry XSE',
 'Canyon',
 'Canyon 4WD',
 'Cayenne',
 'Cayenne S',
 'Cayenne Turbo',
 'Cayman',
 'Cayman GTS',
 'Cayman S',
 'Challenger',
 'Challenger (MDS)',
 'Challenger AWD',
 'Challenger GT AWD',
 'Challenger SRT Hellcat',
 'Challenger SRT Hellcat Redeye',
 'Challenger SRT Hellcat Widebody',
 'Challenger Widebody (MDS)',
 'Charger',
 'Charger (MDS)',
 'Charger AWD',
 'Charger AWD (MDS)',
 'Charger AWD FFV',
 'Charger FFV',
 'Charger SRT Hellcat',
 'Charger SRT Hellcat Widebody',
 'Charger Widebody (MDS)',
 'Cherokee',
 'Cherokee 4X4 Active Drive I',
 'Cherokee 4X4 Active Drive II',
 'Cherokee 4X4 Active Drive Lock',
 'Chiron',
 'Civic Coupe',
 'Civic Coupe Si',
 'Civic Hatchback',
 'Civic Hatchback Sport',
 'Civic Sedan',
 'Civic Sedan Si',
 'Civic Type R',
 'Colorado',
 'Colorado 4WD',
 'Colorado ZR2 4WD',
 'Compass',
 'Compass 4X4',
 'Continental AWD',
 'Continental GT',
 'Continental GT Convertible',
 'Cooper 3 Door',
 'Cooper 5 Door',
 'Cooper Clubman ALL4',
 'Cooper Convertible',
 'Cooper Countryman ALL4',
 'Cooper S 3 Door',
 'Cooper S 5 Door',
 'Cooper S Clubman ALL4',
 'Cooper S Convertible',
 'Cooper S Countryman ALL4',
 'Corolla',
 'Corolla Hatchback',
 'Corolla Hybrid',
 'Corolla LE Eco',
 'Corolla XLE',
 'Corolla XSE',
 'Corsair AWD',
 'Corvette',
 'Corvette Z06',
 'Corvette ZR1',
 'Crosstrek AWD',
 'Cruze',
 'Cruze Diesel',
 'Cruze Hatchback',
 'Cruze Hatchback Diesel',
 'Cruze Hatchback Premier',
 'Cruze Premier',
 'Cullinan',
 'Cullinan Black Badge',
 'DART',
 'DART FFV',
 'DART GT',
 'DART TURBO AERO',
 'DAWN',
 'DB11 AMR',
 'DB11 V12',
 'DB11 V8',
 'DB9',
 'DB9 GT',
 'DBS Superleggera',
 'DISCOVERY SPORT',
 'DURANGO AWD',
 'DURANGO AWD (MDS)',
 'DURANGO AWD FFV',
 'DURANGO AWD SRT',
 'Dawn',
 'Discovery',
 'Discovery Sport',
 'Discovery Sport P250',
 'Discovery Sport P290',
 'Discovery TD6 Diesel',
 'Durango AWD',
 'Durango AWD SRT',
 'E 250 BLUETEC 4MATIC',
 'E 300 4MATIC',
 'E 350 4MATIC',
 'E 350 4MATIC COUPE',
 'E 350 4MATIC WAGON',
 'E 350 CABRIOLET',
 'E 350 COUPE',
 'E 400 4MATIC',
 'E 400 4MATIC CABRIOLET',
 'E 400 4MATIC COUPE',
 'E 400 4MATIC WAGON',
 'E 400 CABRIOLET',
 'E 400 COUPE',
 'E 400 HYBRID',
 'E 450 4MATIC',
 'E 450 4MATIC Cabriolet',
 'E 450 4MATIC Coupe',
 'E 450 4MATIC Wagon',
 'E 550 4MATIC',
 'E 550 CABRIOLET',
 'E 550 COUPE',
 'E 63 AMG 4MATIC',
 'E 63 AMG 4MATIC WAGON',
 'E 63 AMG S 4MATIC',
 'E 63 AMG S 4MATIC WAGON',
 'E-PACE P250',
 'E-PACE P300',
 'E150 VAN FFV',
 'E150 WAGON FFV',
 'E350 WAGON',
 'E350 WAGON FFV',
 'ECLIPSE CROSS',
 'ECLIPSE CROSS 4WD',
 'ECOSPORT',
 'ECOSPORT AWD',
 'EDGE',
 'EDGE (Start/Stop)',
 'EDGE AWD',
 'EDGE SPORT AWD',
 'ELANTRA',
 'ELANTRA COUPE',
 'ELANTRA GT',
 'ENCLAVE',
 'ENCLAVE AWD',
 'ENCORE',
 'ENCORE (LE2 Engine)',
 'ENCORE (LUV Engine)',
 'ENCORE (SIDI with Stop/Start)',
 'ENCORE AWD',
 'ENCORE AWD (LE2 Engine)',
 'ENCORE AWD (LUV Engine)',
 'ENCORE AWD (SIDI with Stop/Start)',
 'ENCORE SPORT TOURING',
 'ENCORE SPORT TOURING AWD',
 'ENVISION AWD',
 'EOS',
 'EQUINOX',
 'EQUINOX AWD',
 'EQUINOX AWD FFV',
 'EQUINOX FFV',
 'EQUUS',
 'ES 300h',
 'ES 350',
 'ES 350 F SPORT',
 'ESCALADE 4WD',
 'ESCALADE AWD',
 'ESCALADE ESV 4WD',
 'ESCALADE ESV AWD',
 'ESCAPE',
 'ESCAPE AWD',
 'ESCAPE FFV',
 'EXPEDITION 4X4',
 'EXPEDITION 4X4 FFV',
 'EXPEDITION EL 4X4',
 'EXPEDITION MAX 4X4',
 'EXPLORER',
 'EXPLORER AWD',
 'EXPLORER AWD (EcoBoost)',
 'EXPLORER FFV',
 'EXPLORER FFV AWD',
 'EXPRESS 1500 CARGO',
 'EXPRESS 1500 CARGO AWD',
 'EXPRESS 1500 CARGO CONV',
 'EXPRESS 1500 CARGO CONV AWD',
 'EXPRESS 1500 PASSENGER',
 'EXPRESS 1500 PASSENGER AWD',
 'EXPRESS 2500 PASSENGER',
 'EXPRESS 2500 PASSENGER FFV',
 'EXPRESS 3500 PASSENGER',
 'EXPRESS 3500 PASSENGER FFV',
 'Eclipse Cross 4WD',
 'EcoSport',
 'EcoSport AWD',
 'Edge',
 'Edge AWD',
 'Elantra',
 'Elantra GT',
 'Enclave',
 'Enclave AWD',
 'Encore',
 'Encore (SIDI with Stop/Start)',
 'Encore AWD',
 'Encore AWD (SIDI with Stop/Start)',
 'Encore GX',
 'Encore GX AWD',
 'Envision AWD',
 'Equinox',
 'Equinox AWD',
 'Escalade 4WD',
 'Escape',
 'Escape AWD',
 'Escape FFV',
 'Escape Hybrid',
 'Escape Hybrid AWD',
 'Expedition 4X4',
 'Expedition MAX 4X4',
 'Explorer AWD',
 'Explorer FFV AWD',
 'Explorer Hybrid AWD',
 'F-150',
 'F-150 (LT Tire Pkg)',
 'F-150 (Payload Pkg)',
 'F-150 4X4',
 'F-150 4X4 (LT Tire Pkg)',
 'F-150 4X4 (Payload Pkg)',
 'F-150 4X4 Limited',
 'F-150 4X4 XL/XLT',
 'F-150 FFV',
 'F-150 FFV (LT Tire Pkg)',
 'F-150 FFV (Payload Pkg)',
 'F-150 FFV 4X4',
 'F-150 FFV 4X4 (LT Tire Pkg)',
 'F-150 FFV 4X4 (Payload Pkg)',
 'F-150 RAPTOR 4WD',
 'F-150 RAPTOR 4X4',
 'F-150 Raptor 4X4',
 'F-PACE 20d',
 'F-PACE 25t',
 'F-PACE 30t',
 'F-PACE 35t',
 'F-PACE S',
 'F-PACE SVR',
 'F-TYPE CONVERTIBLE',
 'F-TYPE CONVERTIBLE R-DYNAMIC',
 'F-TYPE CONVERTIBLE R-DYNAMIC AWD',
 'F-TYPE COUPE',
 'F-TYPE COUPE R-DYNAMIC',
 'F-TYPE COUPE R-DYNAMIC AWD',
 'F-TYPE Convertible',
 'F-TYPE Convertible R-Dynamic',
 'F-TYPE Convertible R-Dynamic AWD',
 'F-TYPE Coupe',
 'F-TYPE Coupe R-Dynamic',
 'F-TYPE Coupe R-Dynamic AWD',
 'F-TYPE P300 Convertible',
 'F-TYPE P300 Coupe',
 'F-TYPE PROJECT 7 CONVERTIBLE',
 'F-TYPE R AWD CONVERTIBLE',
 'F-TYPE R AWD COUPE',
 'F-TYPE R AWD Convertible',
 'F-TYPE R AWD Coupe',
 'F-TYPE R CONVERTIBLE AWD',
 'F-TYPE R COUPE AWD',
 'F-TYPE S CONVERTIBLE',
 'F-TYPE S CONVERTIBLE AWD',
 'F-TYPE S COUPE',
 'F-TYPE S COUPE AWD',
 'F-TYPE SVR AWD Convertible',
 'F-TYPE SVR AWD Coupe',
 'F-TYPE V8 R COUPE',
 'F-TYPE V8 S CONVERTIBLE',
 'FIESTA',
 'FIESTA SFE',
 'FIESTA ST',
 'FIT',
 'FJ CRUISER 4WD',
 'FLEX',
 'FLEX AWD',
 'FLEX AWD (EcoBoost)',
 'FLEX AWD GTDI',
 'FLYING SPUR',
 'FOCUS',
 'FOCUS (Start/Stop)',
 'FOCUS FFV',
 'FOCUS RS AWD',
 'FOCUS SFE FFV',
 'FOCUS ST',
 'FORESTER AWD',
 'FORTE',
 'FORTE (GDI)',
 'FORTE (MPI)',
 'FORTE 5',
 'FORTE KOUP',
 'FORTWO CABRIOLET',
 'FORTWO COUPE',
 'FR-S',
 'FRONTIER',
 'FRONTIER 4WD',
 'FUSION',
 'FUSION (Start/Stop)',
 'FUSION AWD',
 'FUSION HYBRID',
 'Fiesta',
 'Fiesta ST',
 'Fit',
 'Flex',
 'Flex AWD',
 'Flex AWD GTDI',
 'Flying Spur',
 'Forester AWD',
 'Forte',
 'Forte 5',
 'Frontier',
 'Frontier 4WD',
 'Fusion',
 'Fusion Hybrid',
 'G 550',
 'G 63 AMG',
 'G70',
 'G70 AWD',
 'G80 AWD',
 'G90 AWD',
 'GALLARDO COUPE',
 'GENESIS',
 'GENESIS AWD',
 'GENESIS COUPE',
 'GHIBLI',
 'GHIBLI AWD',
 'GHIBLI S',
 'GHIBLI SQ4',
 'GHOST',
 'GHOST EWB',
 'GIULIA',
 'GIULIA AWD',
 'GIULIA QUADRIFOGLIO',
 'GL 350 BLUETEC 4MATIC',
 'GL 450 4MATIC',
 'GL 550 4MATIC',
 'GL 63 AMG',
 'GLA 250 4MATIC',
 'GLA 45 AMG 4MATIC',
 'GLC 300 4MATIC',
 'GLC 300 4MATIC COUPE',
 'GLC 300 4MATIC Coupe',
 'GLE 350d 4MATIC',
 'GLE 350d 4MATIC COUPE',
 'GLE 400 4MATIC',
 'GLE 450 AMG SPORT 4MATIC COUPE',
 'GLE 550 4MATIC',
 'GLK 250 BLUETEC 4MATIC',
 'GLK 350 4MATIC',
 'GLS 450 4MATIC',
 'GLS 550 4MATIC',
 'GOLF',
 'GOLF ALLTRACK',
 'GOLF GTI',
 ...]

In [62]:

# Remove leading and trailing spaces in the 'Model' column
data_prep['Model'] = data_prep['Model'].str.strip()

In [63]:
##check again 

# Get unique values from the 'Model' column and store them in 'unique_values'
unique_values = data_prep['Model'].unique()

# Create an empty list 'array1' to hold the unique values
array1 = []


# Iterate through each unique value and append it to 'array1'
for value in unique_values:
    # print(value)
    array1.append(value)

# Sort the 'array1' to get a list of unique values in alphabetical order
sorted_list = sorted(array1)

sorted_list

['124 SPIDER',
 '124 Spider',
 '1500',
 '1500 (MDS)',
 '1500 4X4',
 '1500 4X4 (MDS)',
 '1500 4X4 DIESEL',
 '1500 4X4 ECODIESEL',
 '1500 4X4 EcoDiesel',
 '1500 4X4 FFV',
 '1500 4X4 eTorque',
 '1500 Classic',
 '1500 Classic 4X4',
 '1500 Classic 4X4 EcoDiesel',
 '1500 Classic 4X4 FFV',
 '1500 Classic EcoDiesel',
 '1500 Classic FFV',
 '1500 DIESEL',
 '1500 ECODIESEL',
 '1500 ECODIESEL HFE',
 '1500 EcoDiesel',
 '1500 FFV',
 '1500 HFE',
 '1500 HFE eTorque',
 '1500 eTorque',
 '200',
 '200 AWD',
 '200 AWD FFV',
 '200 CONVERTIBLE',
 '200 CONVERTIBLE FFV',
 '200 FFV',
 '200 SEDAN',
 '200 SEDAN FFV',
 '228i',
 '228i CABRIOLET',
 '228i COUPE',
 '228i xDRIVE',
 '228i xDRIVE CABRIOLET',
 '228i xDRIVE COUPE',
 '230i CABRIOLET',
 '230i COUPE',
 '230i Cabriolet',
 '230i Coupe',
 '230i xDRIVE CABRIOLET',
 '230i xDRIVE COUPE',
 '230i xDrive Cabriolet',
 '230i xDrive Coupe',
 '300',
 '300 (MDS)',
 '300 AWD',
 '300 AWD (MDS)',
 '300 AWD FFV',
 '300 FFV',
 '300 SRT (MDS)',
 '320i',
 '320i SEDAN',
 '320i xDRIVE',
 '320i xDRIVE SEDAN',
 '328d xDRIVE',
 '328d xDRIVE SEDAN',
 '328d xDRIVE TOURING',
 '328i',
 '328i SEDAN',
 '328i xDRIVE',
 '328i xDRIVE GRAN TURISMO',
 '328i xDRIVE SEDAN',
 '328i xDRIVE TOURING',
 '330i xDRIVE',
 '330i xDRIVE GRAN TURISMO',
 '330i xDRIVE TOURING',
 '330i xDrive',
 '330i xDrive Gran Turismo',
 '330i xDrive Sedan',
 '330i xDrive Touring',
 '335i',
 '335i SEDAN',
 '335i xDRIVE',
 '335i xDRIVE GRAN TURISMO',
 '335i xDRIVE SEDAN',
 '340i',
 '340i xDRIVE',
 '340i xDRIVE GRAN TURISMO',
 '370Z',
 '370Z COUPE',
 '370Z ROADSTER',
 '370Z Roadster',
 '428i CABRIOLET',
 '428i COUPE',
 '428i GRAN COUPE',
 '428i xDRIVE CABRIOLET',
 '428i xDRIVE COUPE',
 '428i xDRIVE GRAN COUPE',
 '430i Coupe',
 '430i xDRIVE CABRIOLET',
 '430i xDRIVE COUPE',
 '430i xDRIVE GRAN COUPE',
 '430i xDrive Cabriolet',
 '430i xDrive Coupe',
 '430i xDrive Gran Coupe',
 '435i CABRIOLET',
 '435i COUPE',
 '435i GRAN COUPE',
 '435i xDRIVE CABRIOLET',
 '435i xDRIVE COUPE',
 '435i xDRIVE GRAN COUPE',
 '440i COUPE',
 '440i Coupe',
 '440i xDRIVE CABRIOLET',
 '440i xDRIVE COUPE',
 '440i xDRIVE GRAN COUPE',
 '440i xDrive Cabriolet',
 '440i xDrive Coupe',
 '440i xDrive Gran Coupe',
 '4C',
 '4C COUPE',
 '4C Coupe',
 '4C SPIDER',
 '4C Spider',
 '4RUNNER (Part-Time 4WD)',
 '4RUNNER 4WD',
 '4RUNNER 4WD (Part-Time 4WD)',
 '4Runner 4WD',
 '4Runner 4WD (Part-Time 4WD)',
 '500',
 '500 ABARTH',
 '500 ABARTH CABRIO',
 '500 ABARTH HATCHBACK',
 '500 CABRIO',
 '500 CABRIO TURBO',
 '500 HATCHBACK',
 '500 HATCHBACK TURBO',
 '500L',
 '500L TURBO',
 '500X',
 '500X AWD',
 '528i',
 '528i SEDAN',
 '528i xDRIVE',
 '528i xDRIVE SEDAN',
 '530i xDRIVE',
 '530i xDrive',
 '530i xDrive Sedan',
 '535d xDRIVE',
 '535d xDRIVE SEDAN',
 '535i xDRIVE',
 '535i xDRIVE GRAN TURISMO',
 '535i xDRIVE SEDAN',
 '540i xDRIVE',
 '540i xDrive',
 '540i xDrive Sedan',
 '550i xDRIVE',
 '550i xDRIVE GRAN TURISMO',
 '550i xDRIVE SEDAN',
 '640i xDRIVE CABRIOLET',
 '640i xDRIVE GRAN COUPE',
 '640i xDRIVE GRAN TURISMO',
 '640i xDrive Gran Coupe',
 '640i xDrive Gran Turismo',
 '650i xDRIVE CABRIOLET',
 '650i xDRIVE COUPE',
 '650i xDRIVE GRAN COUPE',
 '650i xDrive Gran Coupe',
 '740Ld xDRIVE SEDAN',
 '740Li xDRIVE',
 '740Li xDRIVE SEDAN',
 '750Li xDRIVE',
 '750Li xDRIVE SEDAN',
 '750Li xDrive',
 '750Li xDrive Sedan',
 '750i xDRIVE',
 '750i xDRIVE SEDAN',
 '750i xDRIVE SWB',
 '750i xDrive',
 '750i xDrive Sedan',
 '760Li',
 '760Li SEDAN',
 '86',
 '911 CARRERA',
 '911 CARRERA 4',
 '911 CARRERA 4 CABRIOLET',
 '911 CARRERA 4 GTS',
 '911 CARRERA 4 GTS CABRIOLET',
 '911 CARRERA 4S',
 '911 CARRERA 4S CABRIOLET',
 '911 CARRERA CABRIOLET',
 '911 CARRERA GTS',
 '911 CARRERA GTS CABRIOLET',
 '911 CARRERA S',
 '911 CARRERA S CABRIOLET',
 '911 Carrera',
 '911 Carrera 4',
 '911 Carrera 4 Cabriolet',
 '911 Carrera 4 GTS',
 '911 Carrera 4 GTS Cabriolet',
 '911 Carrera 4S',
 '911 Carrera 4S Cabriolet',
 '911 Carrera Cabriolet',
 '911 Carrera GTS',
 '911 Carrera GTS Cabriolet',
 '911 Carrera S',
 '911 Carrera S Cabriolet',
 '911 Carrera T',
 '911 GT2 RS',
 '911 GT3',
 '911 GT3 RS',
 '911 GT3 Touring',
 '911 GT3RS',
 '911 Speedster',
 '911 TARGA 4',
 '911 TARGA 4 GTS',
 '911 TARGA 4S',
 '911 TURBO',
 '911 TURBO CABRIOLET',
 '911 TURBO S',
 '911 TURBO S CABRIOLET',
 '911 TURBO S EXCLUSIVE',
 '911 Targa 4',
 '911 Targa 4 GTS',
 '911 Targa 4S',
 '911 Turbo',
 '911 Turbo Cabriolet',
 '911 Turbo S',
 '911 Turbo S Cabriolet',
 '911 Turbo S Exclusive Cabriolet',
 'A 220',
 'A 220 4MATIC',
 'A 250',
 'A 250 4MATIC',
 'A3',
 'A3 CABRIOLET QUATTRO',
 'A3 Cabriolet quattro',
 'A3 QUATTRO',
 'A3 TDI (modified)',
 'A3 quattro',
 'A4',
 'A4 ALLROAD QUATTRO',
 'A4 QUATTRO',
 'A4 ULTRA',
 'A4 allroad quattro',
 'A4 quattro',
 'A5 CABRIOLET QUATTRO',
 'A5 Cabriolet quattro',
 'A5 QUATTRO',
 'A5 SPORTBACK QUATTRO',
 'A5 Sportback quattro',
 'A5 quattro',
 'A6 QUATTRO',
 'A6 QUATTRO TDI (modified)',
 'A6 allroad',
 'A6 quattro',
 'A7 QUATTRO',
 'A7 QUATTRO TDI (modified)',
 'A7 quattro',
 'A8',
 'A8 QUATTRO',
 'A8 QUATTRO TDI (modified)',
 'A8 TDI (modified)',
 'A8L',
 'A8L QUATTRO',
 'A8L TDI (modified)',
 'ACADIA',
 'ACADIA AWD',
 'ACCENT',
 'ACCORD',
 'ACCORD COUPE',
 'ACCORD HYBRID',
 'ACCORD SEDAN',
 'ACCORD SPORT',
 'ACCORD SPORT/TOURING',
 'ACTIVEHYBRID 3',
 'ACTIVEHYBRID 5',
 'ACTIVEHYBRID 7L',
 'ALLROAD QUATTRO',
 'ALPINA B6 xDRIVE GRAN COUPE',
 'ALPINA B7 xDRIVE',
 'ALPINA B7 xDRIVE LWB',
 'ALPINA B7 xDRIVE SWB',
 'ALTIMA',
 'ALTIMA 3.5',
 'ALTIMA SR',
 'AMG C 43 4MATIC',
 'AMG C 43 4MATIC CABRIOLET',
 'AMG C 43 4MATIC COUPE',
 'AMG C 43 4MATIC Cabriolet',
 'AMG C 43 4MATIC Coupe',
 'AMG C 43 4MATIC Wagon',
 'AMG C 63',
 'AMG C 63 CABRIOLET',
 'AMG C 63 COUPE',
 'AMG C 63 S',
 'AMG C 63 S CABRIOLET',
 'AMG C 63 S COUPE',
 'AMG C 63 S Cabriolet',
 'AMG C 63 S Coupe',
 'AMG CLA 45',
 'AMG CLA 45 4MATIC',
 'AMG CLS 53 4MATIC+',
 'AMG CLS 63 S 4MATIC',
 'AMG E 43 4MATIC',
 'AMG E 53 4MATIC+',
 'AMG E 53 4MATIC+ Cabriolet',
 'AMG E 53 4MATIC+ Coupe',
 'AMG E 53 4MATIC+ Wagon',
 'AMG E 63 S 4MATIC',
 'AMG E 63 S 4MATIC WAGON',
 'AMG E 63 S 4MATIC+',
 'AMG E 63 S 4MATIC+ Wagon',
 'AMG G 63',
 'AMG G 65',
 'AMG GL 63 S',
 'AMG GLA 45',
 'AMG GLA 45 4MATIC',
 'AMG GLC 43 4MATIC',
 'AMG GLC 43 4MATIC COUPE',
 'AMG GLC 43 4MATIC Coupe',
 'AMG GLC 63 S 4MATIC+',
 'AMG GLC 63 S 4MATIC+ Coupe',
 'AMG GLE 43 4MATIC',
 'AMG GLE 43 4MATIC COUPE',
 'AMG GLE 43 4MATIC Coupe',
 'AMG GLE 63 S 4MATIC',
 'AMG GLE 63 S 4MATIC COUPE',
 'AMG GLE 63 S 4MATIC Coupe',
 'AMG GLE 63 S COUPE 4MATIC',
 'AMG GLS 63',
 'AMG GLS 63 4MATIC',
 'AMG GT 53 4MATIC+ Coupe',
 'AMG GT 63 4MATIC+ Coupe',
 'AMG GT 63 S 4MATIC+ Coupe',
 'AMG GT C COUPE',
 'AMG GT C Coupe',
 'AMG GT C ROADSTER',
 'AMG GT C Roadster',
 'AMG GT COUPE',
 'AMG GT R COUPE',
 'AMG GT R Coupe',
 'AMG GT ROADSTER',
 'AMG GT S',
 'AMG GT S COUPE',
 'AMG S 63',
 'AMG S 63 4MATIC',
 'AMG S 63 4MATIC CABRIOLET',
 'AMG S 63 4MATIC COUPE',
 'AMG S 63 4MATIC+',
 'AMG S 63 4MATIC+ Cabriolet',
 'AMG S 63 4MATIC+ Coupe',
 'AMG S 63 CABRIOLET',
 'AMG S 63 COUPE',
 'AMG S 65',
 'AMG S 65 CABRIOLET',
 'AMG S 65 COUPE',
 'AMG S 65 Cabriolet',
 'AMG S 65 Coupe',
 'AMG SL 63',
 'AMG SL 65',
 'AMG SLC 43',
 'AMG SLK 55',
 'ARMADA 4WD',
 'ATLAS',
 'ATLAS 4MOTION',
 'ATS',
 'ATS AWD',
 'ATS-V',
 'AVALON',
 'AVENGER',
 'AVENGER FFV',
 'AVENTADOR COUPE',
 'AVENTADOR COUPE LP 740',
 'AVENTADOR ROADSTER',
 'AVENTADOR ROADSTER LP 740',
 'AVENTADOR S COUPE',
 'AVENTADOR S ROADSTER',
 'Acadia',
 'Acadia AWD',
 'Accent',
 'Accord',
 'Accord Hybrid',
 'Accord Sport/Touring',
 'Alpina B6 xDrive Gran Coupe',
 'Alpina B7 xDrive',
 'Altima',
 'Altima AWD',
 'Altima AWD SR/Platinum',
 'Altima SR/Platinum',
 'Armada 4WD',
 'Arteon 4MOTION',
 'Ascent AWD',
 'Atlas',
 'Atlas 4MOTION',
 'Atlas Cross Sport 4MOTION',
 'Avalon',
 'Aventador Coupe',
 'Aventador Roadster',
 'Aviator',
 'B 250',
 'B 250 4MATIC',
 'BEETLE',
 'BEETLE CONVERTIBLE',
 'BEETLE DUNE',
 'BEETLE DUNE CONVERTIBLE',
 'BEETLE TDI (modified)',
 'BENTAYGA',
 'BOXSTER',
 'BOXSTER GTS',
 'BOXSTER S',
 'BOXSTER SPYDER',
 'BRZ',
 'BRZ tS',
 'Beetle',
 'Beetle Convertible',
 'Beetle Dune',
 'Beetle Dune Convertible',
 'Bentayga',
 'Blazer',
 'Blazer AWD',
 'Boxster',
 'Boxster GTS',
 'Boxster S',
 'C 250',
 'C 250 COUPE',
 'C 300 4MATIC',
 'C 300 4MATIC CABRIOLET',
 'C 300 4MATIC COUPE',
 'C 300 4MATIC Cabriolet',
 'C 300 4MATIC Coupe',
 'C 300 4MATIC FFV',
 'C 300 4MATIC WAGON',
 'C 300 4MATIC Wagon',
 'C 350',
 'C 350 4MATIC',
 'C 350 4MATIC COUPE',
 'C 350 COUPE',
 'C 400 4MATIC',
 'C 450 AMG SPORT 4MATIC',
 'C 63 AMG',
 'C 63 AMG COUPE',
 'C-HR',
 'C-MAX HYBRID',
 'CADENZA',
 'CAMARO',
 'CAMARO 2LS',
 'CAMARO SS',
 'CAMARO Z/28',
 'CAMARO ZL1',
 'CAMRY',
 'CAMRY HYBRID LE',
 'CAMRY HYBRID XLE/SE',
 'CAMRY LE/SE',
 'CAMRY XLE/XSE',
 'CAMRY XSE',
 'CANYON',
 'CANYON 4WD',
 'CARGO VAN FFV',
 'CAYENNE',
 'CAYENNE DIESEL (modified)',
 'CAYENNE GTS',
 'CAYENNE PLATINUM',
 'CAYENNE S',
 'CAYENNE S HYBRID',
 'CAYENNE TURBO',
 'CAYENNE TURBO S',
 'CAYMAN',
 'CAYMAN GT4',
 'CAYMAN GTS',
 'CAYMAN S',
 'CC',
 'CC 4MOTION',
 'CHALLENGER',
 'CHALLENGER (MDS)',
 'CHALLENGER GT',
 'CHALLENGER GT AWD',
 'CHALLENGER GT AWD FFV',
 'CHALLENGER SRT',
 'CHALLENGER SRT (MDS)',
 'CHALLENGER SRT DEMON',
 'CHALLENGER SRT HELLCAT',
 'CHARGER',
 'CHARGER (MDS)',
 'CHARGER AWD',
 'CHARGER AWD (MDS)',
 'CHARGER AWD FFV',
 'CHARGER FFV',
 'CHARGER SRT (MDS)',
 'CHARGER SRT 392 HEMI',
 'CHARGER SRT HELLCAT',
 'CHEROKEE',
 'CHEROKEE 4X4',
 'CHEROKEE 4X4 ACTIVE DRIVE I',
 'CHEROKEE 4X4 ACTIVE DRIVE I FFV',
 'CHEROKEE 4X4 ACTIVE DRIVE II',
 'CHEROKEE 4X4 ACTIVE DRIVE LOCK',
 'CHEROKEE 4X4 FFV',
 'CHEROKEE FFV',
 'CHEROKEE TRAILHAWK 4X4',
 'CHIRON',
 'CITY EXPRESS',
 'CIVIC',
 'CIVIC COUPE',
 'CIVIC COUPE Si',
 'CIVIC HATCHBACK',
 'CIVIC HATCHBACK SPORT',
 'CIVIC HYBRID',
 'CIVIC SEDAN',
 'CIVIC SEDAN Si',
 'CIVIC Si',
 'CIVIC TYPE R',
 'CL 550 4MATIC',
 'CL 63 AMG',
 'CLA 250',
 'CLA 250 4MATIC',
 'CLA 250 4MATIC FFV',
 'CLA 45 AMG',
 'CLA 45 AMG 4MATIC',
 'CLS 400 4MATIC',
 'CLS 450 4MATIC',
 'CLS 550 4MATIC',
 'CLS 63 AMG 4MATIC',
 'CLS 63 AMG S 4MATIC',
 'COLORADO',
 'COLORADO 4WD',
 'COLORADO ZR2 4WD',
 'COMPASS',
 'COMPASS 4X4',
 'COMPASS 4X4 TRAIL RATED',
 'CONTINENTAL AWD',
 'CONTINENTAL GT',
 'CONTINENTAL GT CONVERTIBLE',
 'CONTINENTAL GT SPEED CONVERTIBLE',
 'CONTINENTAL GT3-R',
 'CONTINENTAL GTC',
 'CONTINENTAL SUPERSPORTS',
 'COOPER 3 DOOR',
 'COOPER 5 DOOR',
 'COOPER CLUBMAN',
 'COOPER CLUBMAN ALL4',
 'COOPER CONVERTIBLE',
 'COOPER COUNTRYMAN',
 'COOPER COUNTRYMAN ALL4',
 'COOPER COUPE',
 'COOPER PACEMAN',
 'COOPER ROADSTER',
 'COOPER S 3 DOOR',
 'COOPER S 5 DOOR',
 'COOPER S CLUBMAN',
 'COOPER S CLUBMAN ALL4',
 'COOPER S CONVERTIBLE',
 'COOPER S COUNTRYMAN  ALL4',
 'COOPER S COUNTRYMAN ALL4',
 'COOPER S COUPE',
 'COOPER S PACEMAN ALL4',
 'COOPER S ROADSTER',
 'COROLLA',
 'COROLLA LE ECO (1-mode)',
 'COROLLA LE ECO (2-mode)',
 'COROLLA MATRIX',
 'COROLLA iM',
 'CORVETTE',
 'CORVETTE Z06',
 'CR-V',
 'CR-V AWD',
 'CR-Z',
 'CROSSTOUR AWD',
 'CROSSTREK AWD',
 'CRUZE',
 'CRUZE DIESEL',
 'CRUZE ECO',
 'CRUZE HATCHBACK',
 'CRUZE HATCHBACK DIESEL',
 'CRUZE HATCHBACK PREMIER',
 'CRUZE LIMITED',
 'CRUZE LIMITED ECO',
 'CRUZE PREMIER',
 'CT 200h',
 'CT4',
 'CT4 AWD',
 'CT4-V',
 'CT4-V AWD',
 'CT5',
 'CT5 AWD',
 'CT5-V',
 'CT5-V AWD',
 'CT6',
 'CT6 AWD',
 'CTS',
 'CTS AWD',
 'CTS COUPE',
 'CTS COUPE AWD',
 'CTS SEDAN',
 'CTS SEDAN AWD',
 'CTS SEDAN Vsport',
 'CTS SPORT WAGON',
 'CTS SPORT WAGON AWD',
 'CTS Vsport',
 'CTS-V',
 'CTS-V COUPE',
 'CTS-V SEDAN',
 'CTS-V SPORT WAGON',
 'CX-3',
 'CX-3 (SIL)',
 'CX-3 4WD',
 'CX-30',
 'CX-30 4WD',
 'CX-30 4WD (Cylinder Deactivation)',
 'CX-5',
 'CX-5 (Cylinder Deactivation)',
 'CX-5 (SIL)',
 'CX-5 4WD',
 'CX-5 4WD (Cylinder Deactivation)',
 'CX-5 Diesel 4WD',
 'CX-5 Turbo 4WD',
 'CX-9',
 'CX-9 4WD',
 'Cadenza',
 'Camaro',
 'Camaro SS',
 'Camaro ZL1',
 'Camry',
 'Camry AWD LE/SE',
 'Camry AWD XLE/XSE',
 'Camry Hybrid LE',
 'Camry Hybrid XLE/SE',
 'Camry LE/SE',
 'Camry TRD',
 'Camry XLE/XSE',
 'Camry XSE',
 'Canyon',
 'Canyon 4WD',
 'Cayenne',
 'Cayenne S',
 'Cayenne Turbo',
 'Cayman',
 'Cayman GTS',
 'Cayman S',
 'Challenger',
 'Challenger (MDS)',
 'Challenger AWD',
 'Challenger GT AWD',
 'Challenger SRT Hellcat',
 'Challenger SRT Hellcat Redeye',
 'Challenger SRT Hellcat Widebody',
 'Challenger Widebody (MDS)',
 'Charger',
 'Charger (MDS)',
 'Charger AWD',
 'Charger AWD (MDS)',
 'Charger AWD FFV',
 'Charger FFV',
 'Charger SRT Hellcat',
 'Charger SRT Hellcat Widebody',
 'Charger Widebody (MDS)',
 'Cherokee',
 'Cherokee 4X4 Active Drive I',
 'Cherokee 4X4 Active Drive II',
 'Cherokee 4X4 Active Drive Lock',
 'Chiron',
 'Civic Coupe',
 'Civic Coupe Si',
 'Civic Hatchback',
 'Civic Hatchback Sport',
 'Civic Sedan',
 'Civic Sedan Si',
 'Civic Type R',
 'Colorado',
 'Colorado 4WD',
 'Colorado ZR2 4WD',
 'Compass',
 'Compass 4X4',
 'Continental AWD',
 'Continental GT',
 'Continental GT Convertible',
 'Cooper 3 Door',
 'Cooper 5 Door',
 'Cooper Clubman ALL4',
 'Cooper Convertible',
 'Cooper Countryman ALL4',
 'Cooper S 3 Door',
 'Cooper S 5 Door',
 'Cooper S Clubman ALL4',
 'Cooper S Convertible',
 'Cooper S Countryman ALL4',
 'Corolla',
 'Corolla Hatchback',
 'Corolla Hybrid',
 'Corolla LE Eco',
 'Corolla XLE',
 'Corolla XSE',
 'Corsair AWD',
 'Corvette',
 'Corvette Z06',
 'Corvette ZR1',
 'Crosstrek AWD',
 'Cruze',
 'Cruze Diesel',
 'Cruze Hatchback',
 'Cruze Hatchback Diesel',
 'Cruze Hatchback Premier',
 'Cruze Premier',
 'Cullinan',
 'Cullinan Black Badge',
 'DART',
 'DART FFV',
 'DART GT',
 'DART TURBO AERO',
 'DAWN',
 'DB11 AMR',
 'DB11 V12',
 'DB11 V8',
 'DB9',
 'DB9 GT',
 'DBS Superleggera',
 'DISCOVERY SPORT',
 'DURANGO AWD',
 'DURANGO AWD (MDS)',
 'DURANGO AWD FFV',
 'DURANGO AWD SRT',
 'Dawn',
 'Discovery',
 'Discovery Sport',
 'Discovery Sport P250',
 'Discovery Sport P290',
 'Discovery TD6 Diesel',
 'Durango AWD',
 'Durango AWD SRT',
 'E 250 BLUETEC 4MATIC',
 'E 300 4MATIC',
 'E 350 4MATIC',
 'E 350 4MATIC COUPE',
 'E 350 4MATIC WAGON',
 'E 350 CABRIOLET',
 'E 350 COUPE',
 'E 400 4MATIC',
 'E 400 4MATIC CABRIOLET',
 'E 400 4MATIC COUPE',
 'E 400 4MATIC WAGON',
 'E 400 CABRIOLET',
 'E 400 COUPE',
 'E 400 HYBRID',
 'E 450 4MATIC',
 'E 450 4MATIC Cabriolet',
 'E 450 4MATIC Coupe',
 'E 450 4MATIC Wagon',
 'E 550 4MATIC',
 'E 550 CABRIOLET',
 'E 550 COUPE',
 'E 63 AMG 4MATIC',
 'E 63 AMG 4MATIC WAGON',
 'E 63 AMG S 4MATIC',
 'E 63 AMG S 4MATIC WAGON',
 'E-PACE P250',
 'E-PACE P300',
 'E150 VAN FFV',
 'E150 WAGON FFV',
 'E350 WAGON',
 'E350 WAGON FFV',
 'ECLIPSE CROSS',
 'ECLIPSE CROSS 4WD',
 'ECOSPORT',
 'ECOSPORT AWD',
 'EDGE',
 'EDGE (Start/Stop)',
 'EDGE AWD',
 'EDGE SPORT AWD',
 'ELANTRA',
 'ELANTRA COUPE',
 'ELANTRA GT',
 'ENCLAVE',
 'ENCLAVE AWD',
 'ENCORE',
 'ENCORE (LE2 Engine)',
 'ENCORE (LUV Engine)',
 'ENCORE (SIDI with Stop/Start)',
 'ENCORE AWD',
 'ENCORE AWD (LE2 Engine)',
 'ENCORE AWD (LUV Engine)',
 'ENCORE AWD (SIDI with Stop/Start)',
 'ENCORE SPORT TOURING',
 'ENCORE SPORT TOURING AWD',
 'ENVISION AWD',
 'EOS',
 'EQUINOX',
 'EQUINOX AWD',
 'EQUINOX AWD FFV',
 'EQUINOX FFV',
 'EQUUS',
 'ES 300h',
 'ES 350',
 'ES 350 F SPORT',
 'ESCALADE 4WD',
 'ESCALADE AWD',
 'ESCALADE ESV 4WD',
 'ESCALADE ESV AWD',
 'ESCAPE',
 'ESCAPE AWD',
 'ESCAPE FFV',
 'EXPEDITION 4X4',
 'EXPEDITION 4X4 FFV',
 'EXPEDITION EL 4X4',
 'EXPEDITION MAX 4X4',
 'EXPLORER',
 'EXPLORER AWD',
 'EXPLORER AWD (EcoBoost)',
 'EXPLORER FFV',
 'EXPLORER FFV AWD',
 'EXPRESS 1500 CARGO',
 'EXPRESS 1500 CARGO AWD',
 'EXPRESS 1500 CARGO CONV',
 'EXPRESS 1500 CARGO CONV AWD',
 'EXPRESS 1500 PASSENGER',
 'EXPRESS 1500 PASSENGER AWD',
 'EXPRESS 2500 PASSENGER',
 'EXPRESS 2500 PASSENGER FFV',
 'EXPRESS 3500 PASSENGER',
 'EXPRESS 3500 PASSENGER FFV',
 'Eclipse Cross 4WD',
 'EcoSport',
 'EcoSport AWD',
 'Edge',
 'Edge AWD',
 'Elantra',
 'Elantra GT',
 'Enclave',
 'Enclave AWD',
 'Encore',
 'Encore (SIDI with Stop/Start)',
 'Encore AWD',
 'Encore AWD (SIDI with Stop/Start)',
 'Encore GX',
 'Encore GX AWD',
 'Envision AWD',
 'Equinox',
 'Equinox AWD',
 'Escalade 4WD',
 'Escape',
 'Escape AWD',
 'Escape FFV',
 'Escape Hybrid',
 'Escape Hybrid AWD',
 'Expedition 4X4',
 'Expedition MAX 4X4',
 'Explorer AWD',
 'Explorer FFV AWD',
 'Explorer Hybrid AWD',
 'F-150',
 'F-150 (LT Tire Pkg)',
 'F-150 (Payload Pkg)',
 'F-150 4X4',
 'F-150 4X4 (LT Tire Pkg)',
 'F-150 4X4 (Payload Pkg)',
 'F-150 4X4 Limited',
 'F-150 4X4 XL/XLT',
 'F-150 FFV',
 'F-150 FFV (LT Tire Pkg)',
 'F-150 FFV (Payload Pkg)',
 'F-150 FFV 4X4',
 'F-150 FFV 4X4 (LT Tire Pkg)',
 'F-150 FFV 4X4 (Payload Pkg)',
 'F-150 RAPTOR 4WD',
 'F-150 RAPTOR 4X4',
 'F-150 Raptor 4X4',
 'F-PACE 20d',
 'F-PACE 25t',
 'F-PACE 30t',
 'F-PACE 35t',
 'F-PACE S',
 'F-PACE SVR',
 'F-TYPE CONVERTIBLE',
 'F-TYPE CONVERTIBLE R-DYNAMIC',
 'F-TYPE CONVERTIBLE R-DYNAMIC AWD',
 'F-TYPE COUPE',
 'F-TYPE COUPE R-DYNAMIC',
 'F-TYPE COUPE R-DYNAMIC AWD',
 'F-TYPE Convertible',
 'F-TYPE Convertible R-Dynamic',
 'F-TYPE Convertible R-Dynamic AWD',
 'F-TYPE Coupe',
 'F-TYPE Coupe R-Dynamic',
 'F-TYPE Coupe R-Dynamic AWD',
 'F-TYPE P300 Convertible',
 'F-TYPE P300 Coupe',
 'F-TYPE PROJECT 7 CONVERTIBLE',
 'F-TYPE R AWD CONVERTIBLE',
 'F-TYPE R AWD COUPE',
 'F-TYPE R AWD Convertible',
 'F-TYPE R AWD Coupe',
 'F-TYPE R CONVERTIBLE AWD',
 'F-TYPE R COUPE AWD',
 'F-TYPE S CONVERTIBLE',
 'F-TYPE S CONVERTIBLE AWD',
 'F-TYPE S COUPE',
 'F-TYPE S COUPE AWD',
 'F-TYPE SVR AWD Convertible',
 'F-TYPE SVR AWD Coupe',
 'F-TYPE V8 R COUPE',
 'F-TYPE V8 S CONVERTIBLE',
 'FIESTA',
 'FIESTA SFE',
 'FIESTA ST',
 'FIT',
 'FJ CRUISER 4WD',
 'FLEX',
 'FLEX AWD',
 'FLEX AWD (EcoBoost)',
 'FLEX AWD GTDI',
 'FLYING SPUR',
 'FOCUS',
 'FOCUS (Start/Stop)',
 'FOCUS FFV',
 'FOCUS RS AWD',
 'FOCUS SFE FFV',
 'FOCUS ST',
 'FORESTER AWD',
 'FORTE',
 'FORTE (GDI)',
 'FORTE (MPI)',
 'FORTE 5',
 'FORTE KOUP',
 'FORTWO CABRIOLET',
 'FORTWO COUPE',
 'FR-S',
 'FRONTIER',
 'FRONTIER 4WD',
 'FUSION',
 'FUSION (Start/Stop)',
 'FUSION AWD',
 'FUSION HYBRID',
 'Fiesta',
 'Fiesta ST',
 'Fit',
 'Flex',
 'Flex AWD',
 'Flex AWD GTDI',
 'Flying Spur',
 'Forester AWD',
 'Forte',
 'Forte 5',
 'Frontier',
 'Frontier 4WD',
 'Fusion',
 'Fusion Hybrid',
 'G 550',
 'G 63 AMG',
 'G70',
 'G70 AWD',
 'G80 AWD',
 'G90 AWD',
 'GALLARDO COUPE',
 'GENESIS',
 'GENESIS AWD',
 'GENESIS COUPE',
 'GHIBLI',
 'GHIBLI AWD',
 'GHIBLI S',
 'GHIBLI SQ4',
 'GHOST',
 'GHOST EWB',
 'GIULIA',
 'GIULIA AWD',
 'GIULIA QUADRIFOGLIO',
 'GL 350 BLUETEC 4MATIC',
 'GL 450 4MATIC',
 'GL 550 4MATIC',
 'GL 63 AMG',
 'GLA 250 4MATIC',
 'GLA 45 AMG 4MATIC',
 'GLC 300 4MATIC',
 'GLC 300 4MATIC COUPE',
 'GLC 300 4MATIC Coupe',
 'GLE 350d 4MATIC',
 'GLE 350d 4MATIC COUPE',
 'GLE 400 4MATIC',
 'GLE 450 AMG SPORT 4MATIC COUPE',
 'GLE 550 4MATIC',
 'GLK 250 BLUETEC 4MATIC',
 'GLK 350 4MATIC',
 'GLS 450 4MATIC',
 'GLS 550 4MATIC',
 'GOLF',
 'GOLF ALLTRACK',
 'GOLF GTI',
 'GOLF R',
 'GOLF SPORTWAGEN',
 'GOLF SPORTWAGEN 4MOTION',
 'GOLF SPORTWAGON',
 'GOLF SPORTWAGON TDI (modified)',
 'GOLF TDI (modified)',
 'GOLF WAGON',
 'GOLF WAGON TDI (modified)',
 'GR Supra',
 'GRAND CARAVAN FFV',
 'GRAND CHEROKEE 4X4',
 'GRAND CHEROKEE 4X4 (MDS)',
 'GRAND CHEROKEE 4X4 DIESEL',
 'GRAND CHEROKEE 4X4 FFV',
 'GRAND CHEROKEE 4X4 SRT',
 'GRAND CHEROKEE 4X4 TRACKHAWK',
 'GRAND CHEROKEE SRT 4X4 (MDS)',
 'GRAND CHEROKEE SRT8',
 'GRANTURISMO',
 'GRANTURISMO CONVERTIBLE',
 'GS 200t',
 ...]

In [64]:
data_prep["Transmission"].value_counts()

Transmission
AS6      1141
AS8      1059
M6        774
A6        687
AM7       383
A8        382
AS7       284
A9        265
AV        241
M5        169
AS10      152
AM6       107
AV7        92
AV6        89
A5         79
M7         78
AS9        68
A4         61
A7         46
AM8        45
AV8        34
A10        28
AS5        27
AV10        9
 AS8        6
AM5         4
 AS7        3
 AM7        3
AS4         2
 AV8        2
 AS6        2
 AM6        1
 AM9        1
 A9         1
 AV6        1
 AM8        1
 A8         1
AM9         1
 AS10       1
 AS5        1
Name: count, dtype: int64

In [65]:
# do the similar to the Transmission column too 
data_prep['Transmission'] = data_prep['Transmission'].str.strip()

In [66]:
data_prep["Transmission"].value_counts()

Transmission
AS6     1143
AS8     1065
M6       774
A6       687
AM7      386
A8       383
AS7      287
A9       266
AV       241
M5       169
AS10     153
AM6      108
AV7       92
AV6       90
A5        79
M7        78
AS9       68
A4        61
A7        46
AM8       46
AV8       36
AS5       28
A10       28
AV10       9
AM5        4
AM9        2
AS4        2
Name: count, dtype: int64

In [67]:
### modified the data set more 
# data_prep.to_csv('data/preprocessig_data.csv', index=False)